#!/bin/bash

set -eou pipefail

apt update
apt install -y git zsh procps sudo ca-certificates python3 python3-pip python3-venv curl wget fontconfig ftp gawk

# NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
