#!/bin/bash

set -eou pipefail

apt update
apt install -y zsh sudo ca-certificates python3 python3-pip python3-venv curl wget fontconfig

NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
