#!/bin/zsh

set -e
# setopt xtrace

source $HOME/.dotfiles/dotfiles

# Configure symlink in the home directory
DOTFILES_SYMLINK .zshrc
DOTFILES_SYMLINK .zshrc.local
DOTFILES_SYMLINK .gitconfig.local
DOTFILES_SYMLINK .gitconfig
DOTFILES_SYMLINK .config/starship.toml

mkdir -p ~/.config

# START nala 'replacements for apt'
# if [[ $MACHINE != "Mac" ]]; then
#   INSTALL_CMD nala
#   ALIAS apt "sudo nala"
# f

DOTFILES_PLUGINS=($(ls $HOME/.dotfiles/plugins | xargs -n 1 basename | sed 's/\.zsh$//'))

export LC_COLLATE=C
for i_plugin in "${DOTFILES_PLUGINS[@]}"; do
  i_plugin="$HOME/.dotfiles/plugins/${i_plugin}.zsh"
  START $(basename ${i_plugin%.*}) "$(head -n1 $i_plugin | cut -c 3-)"
  SOURCE "${i_plugin}"
done
FINISH

set +e
